### ISSUE TITLE
MySQL 这一章, 字段类型应该是 byte 而不是 bit 吧

### ISSUE THREAD

**Issue by stormeyes** [colinlet/PHP-Interview-QA#1]
比如 tinyint -- 1 bit, 这肯定是不对的.

tinyint 的取值范围是 -128 to 127, 即 1 byte(8 bit) 的区间, 意味着有2的8次方, 即 256 种排列组合, 用于盛放-128 to 127 的取值.

1 bit 意味着 tinyint 的取值只能是 1 和 0, 这不现实.....

**Comment by shisiying** [comment]
是呀，刚开头看纠错了，估计是byte跟bit没分清
