### ISSUE TITLE
一道面试题，html的三个基本标签是？

### ISSUE THREAD

**Issue by TUSIDENG** [colinlet/PHP-Interview-QA#11]
我答的是head,body和title，感觉有点不对，所以发出来和大家一起讨论。

**Comment by apades** [comment]
第三个应该是doctype声明html格式吧

**Comment by jiancheng132** [comment]
html head body

**Comment by TUSIDENG** [comment]
> 第三个应该是doctype声明html格式吧

应该不是这个

**Comment by TUSIDENG** [comment]
> html head body

这个回答应该是正确的，但如果问的是元素类型，应该回答是block（块极），inline（行内），inline-block（行内块级)元素。
