### ISSUE TITLE
感觉有些问题的答案不是很精准吧

### ISSUE THREAD

**Issue by bapijun** [colinlet/PHP-Interview-QA#3]

**Comment by bapijun** [comment]
看了一下qa那一块的,有些答案其实不算是精准,fork了之后自己也添加一些一些答案

**Comment by colinlet** [comment]
@bapijun 感谢关注。目前还在梳理中，答案有一部分是自己写的，一部分是网上整理，还没有校对过，所以有些答案是会不准确的。有兴趣参与，欢迎加微信群交流~~
1.问题来源实际面试
2.简洁回答
3.深入剖析拓展
正在超这个方向努力中
